### ISSUE TITLE
Stripping options

### ISSUE THREAD

**Issue by pervognsen** [Leandros/VisualStudioStandalone#1]
Thanks for publishing this script! I think it'll be helpful to folks.

I suggest there be options for stripping down the distribution. Here's some really low-hanging fruit:

rd /s /q lib\onecore lib\x86\store lib\x64\store
del lib\x86\msvcurt*.* lib\x86\libconc*.* lib\x64\msvcurt*.* lib\x64\libconc*.*

This reduces the distribution size on my system from 781 MB to 231 MB (and compresses to 22 MB).

It removes things that I don't think most (if any) game developers will use like the Universal Runtime, Windows Store and ConcRT libraries.

**Comment by Leandros** [comment]
Good idea. I went ahead and remove some of the lesser used libraries from the distribution. 

See https://github.com/Leandros/VisualStudioStandalone/commit/e9f7e5bc558cf537d5c396194a8a72da81c6b91a
