### ISSUE TITLE
Default to x64 toolchain

### ISSUE THREAD

**Issue by pervognsen** [Leandros/VisualStudioStandalone#2]
Defaulting to the x64-hosted toolchain (vs the current x86) is IMHO the right choice given the amount of large C++ codebases out there, with massive header-heavy libraries (and the obj/PDB dedup that entails) and link-time optimization that gobbles up memory. It's also pretty common for applications to get a ~10% performance boost on x64 due to the extra registers available despite the extra memory/cache pressure from 64-bit pointers, though I can't say I've tested if x64-hosted MSVC indeed compiles faster--I think the strongest argument for making it the default is simply that it's going to support more codebases out of the box.

**Comment by Leandros** [comment]
Agreed! I went with the x86 as a default to provide the compiler for a wider audience, but after thinking about it again, the user base of developers still running a 32-bit OS is small and getting smaller. Fixed in a7b2adb1a8fa9e31087d83b7a9791852088ee0f0
