### ISSUE TITLE
What to do now ?

### ISSUE THREAD

**Issue by graysuit** [Leandros/VisualStudioStandalone#7]
```
C:\Users\Administrator\Desktop\Visual_Studio>tree
Folder PATH listing for volume Games
Volume serial number is 0000006F A687:83CB
C:.
└───14.25.28610
    ├───bin
    │   └───HostX64
    │       ├───x64
    │       │   └───1033
    │       └───x86
    │           └───1033
    ├───include
    │   ├───cliext
    │   ├───CodeAnalysis
    │   ├───cvt
    │   ├───experimental
    │   ├───Manifest
    │   └───msclr
    │       └───com
    └───lib
        ├───x64
        └───x86
```

@Leandros Sir,
I done making it portable,
No errors came,
Now where do I find visual studio binary ?

**Comment by graysuit** [comment]
I got what I need,
for simple coding and windows exe,
We can use **Visual Studio 2010 Express**,s
It has free key and has so little size like 100 MB and is fast.


https://my.visualstudio.com/Downloads?q=visual%20studio%202010&wt.mc_id=o~msft~vscom~older-downloads

**Comment by Leandros** [comment]
It's working as intended. There will never be a Visual Studio binary included. This is only extracting the compiler itself.

**Comment by graysuit** [comment]
So then what to do with compiler ?
How to use this compiler without binary ?
Because I installed Visual studio in windows 10,
And also wanted to use it in windows 7 as well,
But visual studio won't work when location is changed,
It is not portable.

**Comment by Leandros** [comment]
You compile it using the compiler (CL.EXE). Visual Studio is an IDE. Not a compiler.
